#!/bin/bash

if [ ! -d /etc/letsencrypt/archive/$HOSTNAME ]; then
    cd /srv/letsencrypt
    /letsencrypt-auto certonly --standalone --agree-tos --email $LETSENCRYPT_EMAIL -d $HOSTNAME -d $SERVERNAME
fi

