#!/bin/sh

export ROOT_URL=https://chat.hypatiasoftware.org/
export MONGO_URL=mongodb://localhost:27017/rocketchat
export PORT=80

if ! [ -d /Rocket.Chat/programs/server/node_modules ]; then
	cd /Rocket.Chat/programs/server && npm install
fi

cd /Rocket.Chat && nodejs main.js
