#! /bin/bash                                                                                                                                   
. /usr/lib/fai/subroutines
# assign classes hosts                                                                                                                         

nogrub=0

# use a list of classes for our demo machine                                                                                                   
case $HOSTNAME in
    faiserver)
        echo "FAIBASE DEMO FAISERVER" ;;
    demohost)
        echo "FAIBASE DHCPC DEMO" ;;
    rms)
        echo "FAIBASE DHCPC DEMO XORG TRISQUEL RMS";;
    gnomehost)
        echo "FAIBASE DHCPC DEMO XORG GNOME";;
    atom*)
        echo "FAIBASE DHCPC DEMO" ;;
    bear)
        echo "FAIBASE DHCPC LVM_XEN_SERVER XEN" ;;
    puma)
        echo "FAIBASE DHCPC RAID_XEN_VIRTUAL" ;;
    diskstation*)
	echo "FAIBASE DISKLESS DISKTOOLS SYSADMIN FSF"
        nogrub=1 ;;
    freestation04)
        echo "FAIBASE DISKLESS XORG TRISQUEL WORKSTATION FSF SYSADMIN MV"
        nogrub=1 ;;
    freestation*)
        echo "FAIBASE DISKLESS XORG TRISQUEL WORKSTATION FSF"
        nogrub=1 ;;
    freetop-x60*)
	echo "FAIBASE DHCPC XORG TRISQUEL WORKSTATION FSF"
	;;
    iwikiserver*)
	echo "FAIBASE IKIWIKI SYSADMIN VM"
	nogrub=1
	;;
    jobserver*)
        echo "FAIBASE  SYSADMIN VM"
        nogrub=1
        ;;
    *)  
        echo "FAIBASE DHCPC DEMO XORG GNOME";;
esac

if [ $nogrub -eq 0 ]; then
    (ifclass I386 || ifclass AMD64) && echo GRUB_PC
fi

exit 0
