#! /bin/bash                                                                                                                                   
. /usr/lib/fai/subroutines
# assign classes hosts                                                                                                                         

if (ifclass I386 || ifclass AMD64) ; then
    GRUB="GRUB_PC"
fi

# use a list of classes for our demo machine                                                                                                   
case $HOSTNAME in
    faiserver*)
	echo "FAIBASE FAISEVER SYSADMIN VM"
        ;;
    demohost)
        echo "FAIBASE $GRUB DHCPC DEMO" ;;
    rms)
        echo "FAIBASE $GRUB DHCPC DEMO XORG TRISQUEL RMS";;
    gnomehost)
        echo "FAIBASE $GRUB DHCPC DEMO XORG GNOME";;
    atom*)
        echo "FAIBASE $GRUB DHCPC DEMO" ;;
    bear)
        echo "FAIBASE $GRUB DHCPC LVM_XEN_SERVER XEN" ;;
    puma)
        echo "FAIBASE $GRUB DHCPC RAID_XEN_VIRTUAL" ;;
    diskstation*)
	echo "FAIBASE DISKLESS DISKTOOLS SYSADMIN FSF"
        ;;
    freestation7)
        echo "FAIBASE DISKLESS XORG TRISQUEL WORKSTATION FSF SYSADMIN MV"
        ;;
    freestation06)
        echo "FAIBASE DISKLESS XORG TRISQUEL WORKSTATION FSF SYSADMIN JAPANESE"
        ;;
    freestation*)
        echo "FAIBASE DISKLESS XORG TRISQUEL WORKSTATION FSF"
        ;;
    zoneminder*)
	echo "FAIBASE SYSADMIN FSF ZONEMINDER"
        ;;
    freetop-x60*)
	echo "FAIBASE $GRUB NW_MGR XORG TRISQUEL WORKSTATION FSF"
	;;
    iwikiserver*)
	echo "FAIBASE IKIWIKI SYSADMIN VM"
	;;
    jobserver*)
        echo "FAIBASE JOB SYSADMIN VM"
        ;;
    mysqlserver*)
        echo "FAIBASE KVMGUEST SYSADMIN MYSQLD"
        ;;
    streamstation*)
        echo "FAIBASE $GRUB SYSADMIN STREAM LIBREPLANET"
        ;;
    freetop*)
        echo "FAIBASE $GRUB NW_MGR SYSADMIN XORG TRISQUEL WORKSTATION LIBREPLANET 3DPRINT"
        ;;
    mwikiserver*)
	echo "FAIBASE MEDIAWIKI SYSADMIN VM"
	;;
    ploneserver*)
	echo "FAIBASE PLONE SYSADMIN VM"
	;;
    printserver*)
	echo "FAIBASE CUPS SYSADMIN VM"
	;;
    crmserver*)
	echo "FAIBASE WWW CIVICRM SYSADMIN VM"
	;;
    crmdevserver*)
	echo "FAIBASE WWW CIVICRM SYSADMIN VM MYSQLD"
	;;
    gnusocial*)
	echo "FAIBASE WWW SYSADMIN VM MYSQLD GNUSOCIAL YOURLS"
	;;
    nagios*)
	echo "FAIBASE SYSADMIN VM MYSQLD NAGIOS WWW"
	;;
    shopserver*)
	echo "FAIBASE SYSADMIN KOSA MARIADB WWW"
	;;
    kdev*)
	echo "FAIBASE SYSADMIN KOSA VM MYSQLD PLONE WWW"
	;;
    glamp*)
	echo "FAIBASE MYSQLD PHP5 SYSADMIN WWW"
	;;
    *)  
        echo "FAIBASE"
	;;
esac

exit 0
